### ISSUE TITLE
试了一下demo发现一个问题，就是在有底部虚拟键的设备上面有问题。

### ISSUE THREAD

**Issue by Zhaoyy** [cpoopc/SmoothEmojiKeyBoard#1]
解决方法是计算container height的时候如果有虚拟键还需要减去虚拟键的高度。
检测设备是否有虚拟键和获取虚拟键高度的方法：
http://blog.csdn.net/Mislead/article/details/45037445

**Comment by cpoopc** [comment]
s,我找个时间借个有虚拟键盘的设备试试

**Comment by cpoopc** [comment]
改好了,刚借了个魅族试过,应该没问题了.
thanks提供检测设备是否有虚拟键和获取虚拟键高度的方法
