### ISSUE TITLE
当"动态"的显示或者隐藏navigationbar

### ISSUE THREAD

**Issue by iielse** [cpoopc/SmoothEmojiKeyBoard#2]
checkDeviceHasNavigationBar方法中 
String navBarOverride = (String) m.invoke(systemPropertiesClass, "qemu.hw.mainkeys");
在华为Mate7 和 魅族M463C中得到的结果是 ""。 
这种情况下 hasNavigationBar 最后的结果都是true。
在华为Mate7中在navigationbar之上将会有一片和navigationbar等高空白区域。

在魅族M463C中打开设置，辅助功能，开启智能隐藏Smartbar。
回到之前界面中将会有一片和navigationbar等高空白区域。

**Comment by cpoopc** [comment]
fix.
ps:你是QA吗?..这么多机子可以测

**Comment by iielse** [comment]
我这里主要有HTC，华为，三星，小米，魅族等几种机型 等我验证一下。
1、现在的代码在魅族M463C中会被遮挡：华为Mate7显示正常。
在 onMeasure 中
if (!initFrameHeight) {
            frame = getFrame();
            mNavigationBarHeight = getNavigationBarHeight(getContext());
           【 frame.getLayoutParams().height = getMeasuredHeight();】
            initFrameHeight = true;
} 
如果这样写【frame.getLayoutParams().height = getMeasuredHeight() - mNavigationBarHeight;】
魅族M463C中显示正常：华为Mate7多出一段空白区域。

我打算根据 android.os.Build 来“兼容” 。  你慢慢研究吧
ps:   android.os.Build.BRAND  "Meizu"

2、动态切换的问题
1)在魅族M463C中打开设置-辅助功能-隐藏Smartbar。会多出一段空白区域。
2)在华为Mate7中动态显示隐藏navigationbar。输入区域缺少对应的变化。比如：当navigationbar显示的时候输入区域正常显示时，此时隐藏navigationbar会多出一段空白区域;当navigationbar隐藏的时候输入区域正常显示时，此时显示navigationbar输入区域会被遮挡
我试过把代码中onMeasure initFrameHeight = true;注释。 就是每次都调用那一串代码。这个时候
输入区的高度会对应动态变化。 但是点击输入框的时候，显示会有问题。\

**Comment by cpoopc** [comment]
看来是还有问题..我是用模拟器调试的,等我借个机子调调

**Comment by cpoopc** [comment]
@iielse 我借了台魅蓝note,发现是因为他显示navitionbar时, DecorView高度会变小.魅族上面应该是可以了.
不过没有其他可以隐藏navitionbar的机型可以测试,可以麻烦你那么试看看华为不?
理论上应该是没问题..

**Comment by cpoopc** [comment]
又借了台华为,华为和魅族不一样,他显示navitionbar时, DecorView高度不会变小.修改了代码.

**Comment by iielse** [comment]
在魅族M463C中打开设置-辅助功能-隐藏Smartbar。这个试过没有？
![Uploading image.png…]()

**Comment by cpoopc** [comment]
我是隐藏/显示悬浮球来控制的,悬浮球隐藏,navitionbar就会显示,这跟smartbar有区别吗?

**Comment by cpoopc** [comment]
[Uploading image.png…]()
图片没上传成功?

**Comment by iielse** [comment]
QQ 多少

**Comment by cpoopc** [comment]
303727604

**Comment by iielse** [comment]
#2 已经被up主已经完美解决
